### PR TITLE
Calculate replication factor for the whole topic instead of single partition

### PR DESCRIPTION
**Pull request by CyberDem0n**
Couple of times we had situations when there were 4 brokers assigned for
one partition. It has happened when one of the kafka nodes was
terminated while another node was doing rebalancing. New node was not
able to start rebalancing because NotEnoughBrokersException was raised
and process of rebalancing didn't even started.
As a simple workaround of such situation we must calculate replication
factor for all partitions of one topic and choose most common value.

Example: {'0': [1,2,3], '1': [1,2,3], '2': [1,2,3,4], '3': [2,3,4]}
replication factor for all partitions must be 3, because there are 3
partitions with replication factor 3 and only one with replication
factor 4.

### CODE REVIEW

**Comment by drummerwolli** [comment]
maybe we don't even need to use the most common value, but the lowest value per topic? if there are more broken partitions than healthy ones, we would increase the replication factor, which might not be favorable ...

**Comment by CyberDem0n** [comment]
So far we(aruha) had  situation with "broken" partitions two times and in all cases that was just one broken partition.

**Comment by drummerwolli** [comment]
yeah, but we had already different scenarios. it should make no difference, or? can you adjust the code?

**Comment by CyberDem0n** [comment]
I just want to avoid reducing of replication factor.
But actually there is one issue with this code: it could happen that more then one value would be in the top of most common values...

**Pull request merged**
