### PR TITLE
Add kafka health health check to the appliance

### PR DESCRIPTION
**Pull request by CyberDem0n**
Health check simply checks that there are not partitions which are
stored on brokers which are not registered in zookeeper.
As a result it returns array of "dead broker" id's.
If there are no dead brokers array would be empty.

Usage: curl http://buku-<stack-version>.<team-name>.zalan.do:8080

### CODE REVIEW

**Comment by drummerwolli** [comment]
this is basically the start for https://github.com/zalando/saiki-buku/issues/21 ... can we make this more generic, i.e. make it available at ...zalan.do:8080/broken_partitions ??? we might wanna add more status updates to one endpoint ...

**Comment by CyberDem0n** [comment]
Currently it runs the same handler for every http GET request, i.e. zalan.do:8080/broken_partitions will work fine.
Later we can introduce as many endpoins as you want.

**Comment by drummerwolli** [comment]
cool!

**Comment by CyberDem0n** [comment]
De facto we are already using Exhibitor to run ZooKeeper cluster so I don't see any reason not to make it an requirement.
Your approach with updating ENV variables from script running in the background will not really work. ENV variables are only visible from the current process or from the processes which were executed by your process. In case if we are running long taks (for example rebalance_partitions), this process will never see your changes.

**Comment by chutium** [comment]
this ENV variable is mainly used for checking if zk hosts are changed:
https://github.com/CyberDem0n/saiki-buku/blob/feature/healthcheck/start_kafka_and_reassign_partitions.py#L72-L73

because kafka brokers are started with a properties file, which has the IP of zk hosts, if this IP list changed, we need to change this IP list string in the property config file, then restart the broker process

if we use Exhibitor API, no ENV variable or something, it will be not easy to check if this variable changed.

so, i would say, Exhibitor API, or AWS API, is not important, current implementation with AWS API in ```generate_zk_conn_str.py``` looks a little bit easier... (I just mean lines of code... : )

but an ENV variable for zk connection str is needed.

**Comment by drummerwolli** [comment]
was touched already also by https://github.com/zalando/saiki-buku/issues/12

**Pull request merged**
